const router = [
  {
    title: "基础配置管理",
    icon: 'PicLeftOutlined',
    key: "/home/user",
    fatherNode:'无',
    email:'235667',
    type:'父',
    sord:'1',
    describe:'针对于基本服务的配置',
    children: [
      {
        key: "/home/user/userOption",
        icon: 'UserOutlined',
        title: "用户管理",
        fatherNode:'基础配置管理',
        email:'235667',
        type:'子',
        sord:'11',
        describe:'用户的基本信息',
      },
      {
        key: "/home/user/menu",
        icon: 'PicCenterOutlined',
        title: "菜单管理",
        fatherNode:'基础配置管理',
        email:'235667',
        type:'子',
        sord:'12',
        describe:'菜单的配置',
      },
      {
        key: "/home/user/roleAuthorization",
        icon: 'UsergroupAddOutlined',
        title: "角色权限管理",
        fatherNode:'基础配置管理',
        email:'235667',
        type:'子',
        sord:'13',
        describe:'角色权限的配置',
      },
      {
        key: "/home/user/userType",
        icon: 'GithubOutlined',
        title: "角色类型管理",
        fatherNode:'基础配置管理',
        email:'235667',
        type:'子',
        sord:'14',
        describe:'角色类型的配置',
      },
      {
        key: "/home/user/actionLog",
        icon: 'BranchesOutlined',
        title: "操作日志",
        fatherNode:'基础配置管理',
        email:'235667',
        type:'子',
        sord:'15',
        describe:'操作日志查看',
      },
      {
        key: "/home/user/onlineUser",
        icon: 'CommentOutlined',
        title: "在线用户",
        fatherNode:'基础配置管理',
        email:'235667',
        type:'子',
        sord:'16',
        describe:'用户的在线数查看',
      },
    ],
  },
  {
    title: "服务权限管理",
    icon: 'InsertRowRightOutlined',
    key: "/home/navigation",
    fatherNode:'无',
    email:'235668',
    type:'父',
    sord:'2',
    describe:'服务权限管理',
    children: [
      {
        key: "/home/navigation/dropdown",
        icon: 'InsuranceOutlined',
        title: "服务管理",
        fatherNode:'服务权限管理',
        email:'235668',
        type:'子',
        sord:'11',
        describe:'服务权限的配置',
      }
    ],
  },
  {
    title: "监控模块管理",
    icon: 'BulbOutlined',
    key: "/home/entry",
    fatherNode:'无',
    email:'235669',
    type:'父',
    sord:'3',
    describe:'监控模块管理',
    children: [
      {
        key: "/home/entry/form/basic-form",
        icon: 'TagsOutlined',
        title: "服务注册中心",
        fatherNode:'监控模块管理',
        email:'235669',
        type:'子',
        sord:'11',
        describe:'用户自行注册的配置',
      },
      {
        key: "/home/entry/form/step-form1",
        icon: 'NodeIndexOutlined',
        title: "服务状态监控",
        fatherNode:'监控模块管理',
        email:'235669',
        type:'子',
        sord:'12',
        describe:'服务状态监控',
      },
      {
        key: "/home/entry/form/step-form2",
        icon: 'RiseOutlined',
        title: "服务链路监控",
        fatherNode:'监控模块管理',
        email:'235669',
        type:'子',
        sord:'13',
        describe:'服务链路监控',
      },
    ],
  }
];

export default router;